### PR TITLE
Documentation deployment diagram fixed

### PR DESCRIPTION
**Pull request by UO289930**
Github box taken out of Ubuntu Server box

### CODE REVIEW

**Comment by plg22** [comment]
The diagram is good, but when I build the docs I get an error from section 5 onwards, where the scheme of the docs is broken, don't you have that problem?

**Comment by UO289930** [comment]
I cannot make the build because I get errors with diagrams when building due to graphviz. Let me check still

**Comment by UO289930** [comment]
Please, check now thta everything is ok

**Comment by plg22** [comment]
Now it works fine

**Pull request merged**
